baseURL = "http://zie.one/"
languageCode = "en-us"
staticDir = ["static" ]
defaultContentLanguageInSubdir=true
defaultContentLanguage="en"
theme="zie"
# Pagination
paginate = 3
paginatePath = "page"
[permalinks]
  post = "/:year/:month/:title/"

title = "Zie.One"
copyright = "© 2018 Copyright zie.one"
# English
[languages.en]
  languageName = "English"
# Catalan
[languages.cat]
  languageName = "Català"
# Other params
[params]
  # Display post summaries instead of content in list templates (default: true)
  # truncate = false

  [related]

# Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
threshold = 80

# To get stable "See also" sections we, by default, exclude newer related pages.
includeNewer = false

# Will lower case keywords in both queries and in the indexes.
toLower = false

[[related.indices]]
name = "keywords"
weight = 150
[[related.indices]]
name  = "author"
toLower = true
weight = 30
[[related.indices]]
name  = "tags"
weight = 100
[[related.indices]]
name  = "date"
weight = 10
pattern = "2006"