+++
categories = ["SSB", "Main"]
date = "2018-08-12"
description = "Secure Scuttlebutt "
title = "Secure Scuttlebutt"
+++

Scuttlebut and this website are open to the public. For more information see link:{{< relref "legal.en.adoc" >}}[our legal page]. 

We run a https://www.scuttlebutt.nz/[Scuttlebut] pub, as a way for 
	us to all connect with each other. Allows for public and private communication and works off-line.

There is a detailed https://www.scuttlebutt.nz/getting-started.html[Getting Started Guide] which is recommended if you've got a few minutes.
		
If you just need to get up and running ASAP here's what you need to know:

== Quick Start

* http://dinosaur.is/patchwork-downloader/[Install Patchwork].
* Boot it up and set up your profile.
* Click "+ Join Pub" in the top left corner of Patchwork and paste in the invite code below.
* Explore by browsing public posts and channels, expand into your extended network (Click on More > Extended Network).
* Introduce yourself on the #new-people channel.
* Follow people you find interesting. You will download content authored by everyone you follow, and everyone who they follow.
* Have fun, and be respectful of others. The scuttleverse is a nice place.

== Your Invite code:
....
zie.one:8008:@tgzHDm9HEN0k5wFRLFmNPyGZYNF/M5KpkZqCRhgowVE=.ed25519~/lJfSYpAfISN3iBxoL71Q7gL+rTaYXfcXJ4cOEb2E2E=
....

This service is paid for out of my own pocket, currently direct costs are $10/month. Donations welcome.
If you are interested in how we run SSB on the server, see our link:{{ <relref "setup.en.adoc">}}[Setup page].

