+++
date = "2018-08-12"
title = "Passwords"
+++

== Storing user passwords

Use scrypt if possible for storing users passwords in your authentication system, otherwise PBKDF2 or bcrypt.

Sources:

"scrypt is asymptotically much more expensive to crack." -cpercival via (https://news.ycombinator.com/item?id=9593916)

"I skip bcrypt because the only reason to not use scrypt is if you need a US Government endorsed scheme. But yeah, it's (slightly) better than PBKDF2." -cpercival via https://news.ycombinator.com/item?id=16748400

Then bcrypt or PBKDF2
"bcrypt is asymptotically marginally more expensive to crack than PBKDF2, but not enough to matter; I'm guessing tptacek's point here is that bcrypt has more library support available (despite PBKDF2 being the de jure standard). I wouldn't say there's a strong argument in either direction." -cpercival via https://news.ycombinator.com/item?id=9593916

"scrypt has nice properties that bcrypt doesn't, and gets those properties by design; it turns out that in practice right now bcrypt has some nice properties too, though they seem accidental. We're using scrypt at Starfighter, even though we have to go through a (very minor) bit of trouble to get it. They're all fine though." -tptacek via (https://news.ycombinator.com/item?id=9593916) May 23, 2015


== Keeping your passwords safe

If you need to generate passwords, or store them to use, use a password manager.

In general when generating passwords, you want every site/resource to have a unique password that is randomly generated and is as long as possible(64 characters is a great length!).

Password managers to check out:

* link:https://1password.com/[1Password] Windows/macOS/Mobile. Linux sort of supported via 1Password X.  Paid subscription, not OSS but very well regarded.
* link:https://www.vaultproject.io/[Vault] OSS/Enterprise. Multi-platform, does WAY more than only store passwords. Well regarded and audited. Password only link:https://github.com/adobe/cryptr[GUI] and link:https://bitbucket.org/zie/vpw[CLI]'s available.
* link:https://www.passwordstore.org/[pass] *NIX, OSS, uses GPG, CLI mostly, UI options 3rd party, browser integration hard. Well regarded.
* link:https://keepassxc.org/[KeepassXC] OSS, Multi-platform, browser integration possible. Well regarded. Mobile integration difficult.
* link:https://bitwarden.com/[Bitwarden] OSS, Great browser, mobile integration. GUI, CLI, etc. all from same developers. not yet well researched or audited.
